CREATE TABLE CLIENTE (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR(100)
);

CREATE TABLE PRODUTO (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   DESCRIPTION VARCHAR(100),
   UNIT_PRICE NUMERIC(20, 2)
);

CREATE TABLE PEDIDO (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   ID_CLIENT INTEGER REFERENCES CLIENTE (ID),
   DATE_PEDIDO TIMESTAMP,
   TOTAL NUMERIC(20, 2)
);

CREATE TABLE ITEM_PEDIDO (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   ID_PEDIDO INTEGER REFERENCES PEDIDO (ID),
   ID_PRODUTO INTEGER REFERENCES PRODUTO (ID),
   AMOUNT INTEGER
);

